experiment:
  gpu: 1 # Run on GPU
  #                                           #
  # Dataset pre-processing and configuration  #
  #                                           #
  dataset: movielens
  data_config:
    strategy: fixed
    train_path: ../../data/dataset/ml_small_2018/splitting/0/subset_train_230.tsv
    test_path: ../../data/dataset/ml_small_2018/splitting/0/test.tsv
  top_k: 50
  #                   #
  # Evaluation Setup  #
  #                   #
  evaluation:
    cutoffs: [5, 10, 20]
    simple_metrics: [nDCG, Recall, Precision, nDCGRendle2020, HR, F1, MAP, MAR, MRR, ACLT, APLT, ARP, PopREO, PopRSP, ItemCoverage, NumRetrived, UserCoverage, Gini, SEntropy, EFD, EPC]
    paired_ttest: True
    wilcoxon_test: True
  print_results_as_triplets: True
  external_models_path: ../external/models/__init__.py
  #               #
  # Models Setup  #
  #               #
  models:
    #                                                             #
    # RecommendationFolder to compute metrics on the best models  #
    #                                                             #
#    ProxyRecommender:
#      path: ../data/dataset/facebook_book/v2/gpt-3.5-turbo-1106/clean/EXP_1_w_duplicate.tsv
    RecommendationFolder:
      folder: ../data/dataset/ml_small_2018/v2/gpt-3.5-turbo-1106/ProxyDir/clean_inverted_rank

  #path_output_rec_result: this/is/the/path/
  #path_output_rec_weight: this/is/the/path/
  #path_output_rec_performance: .
  #path_log_folder: .